// Post-build SRI injector.
//
// Vite emits content-hashed filenames under /assets/ (main-<hash>.js, etc.)
// but does NOT add integrity= attributes to the <script src> / <link href>
// references in dist/*.html. Content-hashed filenames bind filename to bytes
// only if the build is honest. Once HTML is served, an attacker who can
// rewrite responses (compromised Caddy, malicious sidecar, CDN cache
// poisoning, a misconfigured edge proxy serving an alternate origin for
// /assets/*) can swap the bytes under the same filename with no client-side
// detection.
//
// This script walks each dist/*.html, finds <script>/modulepreload/stylesheet
// references into /assets/, computes sha384 over the on-disk bytes, and
// injects integrity= (+ crossorigin if missing) before the file is served.
//
// Skipped:
//   - /config.js: runtime-generated by entrypoint.sh from envs, hash varies.
//   - /js/eruda-loader.js: already has hand-pinned SRI in the source HTML.
//   - non-/assets/ paths (icon, favicon, etc.)
//
// Not a defense against a compromised builder: the SRI is emitted by the
// same build that produces the assets.

import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(__dirname, 'dist');

async function sha384(filePath) {
  const buf = await readFile(filePath);
  return 'sha384-' + createHash('sha384').update(buf).digest('base64');
}

// Match <script ... src="/assets/foo.js" ...></script>
//   and <link ... href="/assets/foo.css" ...>
//   and <link rel=modulepreload ... href="/assets/foo.js" ...>
// We do NOT use a real HTML parser to keep the dep set at zero: vite-emitted
// HTML is well-formed and the regex shape is tightly constrained.
const TAG_RE = /<(script|link)\b([^>]*?)\s(src|href)="(\/assets\/[^"]+)"([^>]*?)\s*\/?>/g;

function injectAttrs(prefix, attrs, attrName, url, suffix, integrity) {
  // If integrity is already present, leave it alone (operator may have
  // pinned a hash manually).
  if (/\sintegrity\s*=/.test(attrs + suffix)) return null;
  const hasCrossorigin = /\scrossorigin(\s|=|>)/.test(attrs + suffix);
  const cross = hasCrossorigin ? '' : ' crossorigin="anonymous"';
  return `<${prefix}${attrs} ${attrName}="${url}"${suffix} integrity="${integrity}"${cross}>`;
}

async function processHtml(htmlPath) {
  const src = await readFile(htmlPath, 'utf8');
  const replacements = [];
  let m;
  TAG_RE.lastIndex = 0;
  while ((m = TAG_RE.exec(src)) !== null) {
    replacements.push({ match: m[0], tag: m[1], attrs: m[2], attrName: m[3], url: m[4], suffix: m[5] });
  }
  let out = src;
  for (const r of replacements) {
    const filePath = join(DIST, r.url.replace(/^\//, ''));
    const hash = await sha384(filePath);
    const replacement = injectAttrs(r.tag, r.attrs, r.attrName, r.url, r.suffix, hash);
    if (replacement === null) continue;
    out = out.replace(r.match, replacement);
  }
  if (out !== src) {
    await writeFile(htmlPath, out, 'utf8');
    console.log(`[postbuild] injected SRI into ${htmlPath.replace(DIST, 'dist')} (${replacements.length} ref(s))`);
  }
}

// Generate dist/<dir>/manifest.json with sha384 of each ORT runtime asset.
// backend.js fetches this at startup, verifies each *.{mjs,wasm} blob, and
// hands ORT the verified bytes via wasmPaths. Without this manifest, a
// serving-path compromise could swap the ~11 MB jsep.wasm for an
// attacker-built ML runtime that exfiltrates PCM at inference time.
// Covers the vendored runtime under dist/ort/.

async function emitOrtManifest() {
  const dirName = 'ort';
  const ortDir = join(DIST, dirName);
  let entries;
  try {
    entries = await readdir(ortDir);
  } catch (_) {
    console.log(`[postbuild] no dist/${dirName}/ directory, skipping ORT manifest`);
    return;
  }
  const targets = entries.filter(n => /\.(mjs|wasm)$/.test(n));
  const manifest = {};
  for (const name of targets) {
    const bytes = await readFile(join(ortDir, name));
    manifest[name] = 'sha384-' + createHash('sha384').update(bytes).digest('base64');
  }
  await writeFile(join(ortDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  console.log(`[postbuild] wrote dist/${dirName}/manifest.json (${targets.length} entries)`);
}

// Generate dist/.well-known/asset-integrity.json with sha384 of any
// non-/assets/, non-/ort/ files that are loaded at runtime via paths the
// browser does not check against the HTML's SRI chain:
//   - /pcm-recorder-worklet.js: AudioWorklet.addModule() runs the worklet
//     in the AudioWorkletGlobalScope with full access to raw PCM samples,
//     and a tampered worklet would leak audio undetected.
//   - /sherpa-onnx/*: the lazily-loaded speaker-diarization engine (a full
//     ML runtime + its emscripten glue), fetch-verified by lib/diarizer.js
//     before it is evaluated, same posture as the ORT wasm. Keyed by their
//     `sherpa-onnx/<name>` subpath so they never collide with bare names.
async function emitAssetIntegrity() {
  const targets = [
    'pcm-recorder-worklet.js',
    'sherpa-onnx/sherpa-onnx-wasm-main-speaker-diarization.js',
    'sherpa-onnx/sherpa-onnx-speaker-diarization.js',
    'sherpa-onnx/sherpa-onnx-wasm-main-speaker-diarization.wasm',
  ];
  const manifest = {};
  for (const name of targets) {
    try {
      manifest[name] = await sha384(join(DIST, name));
    } catch (_) {
      // file may not be present in some dev builds; skip silently.
    }
  }
  if (Object.keys(manifest).length === 0) {
    console.log('[postbuild] no eligible loose runtime assets, skipping integrity manifest');
    return;
  }
  const dir = join(DIST, '.well-known');
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, 'asset-integrity.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  console.log(`[postbuild] wrote dist/.well-known/asset-integrity.json (${Object.keys(manifest).length} entries)`);
}

async function main() {
  const entries = await readdir(DIST, { withFileTypes: true });
  const htmls = entries.filter(e => e.isFile() && e.name.endsWith('.html')).map(e => join(DIST, e.name));
  if (htmls.length === 0) {
    console.error('[postbuild] no .html files found in dist/. Did you run vite build?');
    process.exit(1);
  }
  for (const h of htmls) await processHtml(h);
  await emitOrtManifest();
  await emitAssetIntegrity();
}

// Run only when invoked as a script (node postbuild.mjs), so importing this
// module from a test cannot trigger a build's side effects.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(err => {
    console.error('[postbuild] failed:', err);
    process.exit(1);
  });
}
