// Runtime + build-time config indirection.
// In production, /config.js (generated by docker entrypoint) sets window.__CONFIG__.
// In dev, that file is absent and we fall back to import.meta.env (Vite-substituted at build).
const runtime = typeof window !== 'undefined' ? (window.__CONFIG__ || {}) : {};

export const CONFIG = {
  VITE_DEV_MODE: runtime.VITE_DEV_MODE ?? import.meta.env.VITE_DEV_MODE,
  VITE_DICTATION_DEVICE_SUPPORT: runtime.VITE_DICTATION_DEVICE_SUPPORT ?? import.meta.env.VITE_DICTATION_DEVICE_SUPPORT,
  VITE_MODEL_REPO: runtime.VITE_MODEL_REPO ?? import.meta.env.VITE_MODEL_REPO,
  VITE_MODEL_REVISION: runtime.VITE_MODEL_REVISION ?? import.meta.env.VITE_MODEL_REVISION,
  VITE_MODEL_SOURCE: runtime.VITE_MODEL_SOURCE ?? import.meta.env.VITE_MODEL_SOURCE,
  VITE_ANALYTICS_URL: runtime.VITE_ANALYTICS_URL ?? import.meta.env.VITE_ANALYTICS_URL,
  VITE_ANALYTICS_WEBSITE_ID: runtime.VITE_ANALYTICS_WEBSITE_ID ?? import.meta.env.VITE_ANALYTICS_WEBSITE_ID,
  // Every new VITE_* key the operator can set MUST be added here, otherwise
  // entrypoint.sh dutifully writes it into window.__CONFIG__ and consumers
  // (main.jsx, App.jsx, ...) silently receive `undefined` because this object
  // is the only export they see. Past omission: VITE_ANALYTICS_SRI (see F-22).
  VITE_ANALYTICS_SRI: runtime.VITE_ANALYTICS_SRI ?? import.meta.env.VITE_ANALYTICS_SRI,
  // 'false' disables the HTTPS-relay fallback race in remote-webrtc.js
  // (anything else, including unset, keeps it enabled). Server-side
  // RELAY_ENABLE remains the master gate.
  VITE_RELAY_ENABLE: runtime.VITE_RELAY_ENABLE ?? import.meta.env.VITE_RELAY_ENABLE,
  // 'true' opts INTO the composed WASM decode pipeline (App.jsx): the decode
  // worker also runs on the WASM backend, composed with the encode pool.
  // Anything else (or unset) keeps it WebGPU-only, which is the default
  // because the composed shape measured as a wash on wall clock.
  VITE_WASM_DECODE_PIPELINE: runtime.VITE_WASM_DECODE_PIPELINE ?? import.meta.env.VITE_WASM_DECODE_PIPELINE,
  // 'true' enables the "send this benchmark report to the maintainer" button in
  // the sidebar Benchmark section. The entrypoint derives it from the operator
  // setting BENCHMARK_REPORTS_DIR (the folder the signaling sidecar writes
  // reports into), so the button only exists where a receiver exists. Anything
  // else (or unset) leaves the section copy-only: it still benchmarks, it just
  // never offers to transmit anything.
  VITE_BENCHMARK_UPLOAD: runtime.VITE_BENCHMARK_UPLOAD ?? import.meta.env.VITE_BENCHMARK_UPLOAD,
  // Default curated phrase-boost list to pre-select for a fresh visitor (no
  // saved boost choice yet). A bare name or a "<name>.txt"; the UI normalises
  // and validates it against the served manifest. Overridable per-link via the
  // ?phrase_boost= query param. Never overrides a returning user's saved choice.
  // The container fails to start if this names a list it isn't serving.
  VITE_PHRASE_BOOST_DEFAULT: runtime.VITE_PHRASE_BOOST_DEFAULT ?? import.meta.env.VITE_PHRASE_BOOST_DEFAULT,
  // Speaker-diarization models (lib/diarizationModels.js). The two ONNX models
  // ride the same hub + /models fallback as the Parakeet weights. Defaults are
  // un-gated, hub-resolvable HF mirrors; override to self-host or swap models.
  VITE_DIARIZATION_SEG_REPO: runtime.VITE_DIARIZATION_SEG_REPO ?? import.meta.env.VITE_DIARIZATION_SEG_REPO,
  VITE_DIARIZATION_SEG_FILE: runtime.VITE_DIARIZATION_SEG_FILE ?? import.meta.env.VITE_DIARIZATION_SEG_FILE,
  VITE_DIARIZATION_EMB_REPO: runtime.VITE_DIARIZATION_EMB_REPO ?? import.meta.env.VITE_DIARIZATION_EMB_REPO,
  VITE_DIARIZATION_EMB_FILE: runtime.VITE_DIARIZATION_EMB_FILE ?? import.meta.env.VITE_DIARIZATION_EMB_FILE,
  // Not operator-settable: the docker entrypoint stamps this with the container
  // start time (ISO 8601) when it generates /config.js, so the dev banner can
  // tell visitors how long ago the instance was last restarted. Absent outside
  // docker (dev server has no /config.js), so the banner falls back gracefully.
  CONTAINER_STARTED_AT: runtime.CONTAINER_STARTED_AT,
};
